name = "armoury-crate"
compatibility_date = "2024-04-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
BUNGIE_CLIENT_ID = "51437"
BUNGIE_API_KEY = "fc889064fa9a4020a74af3a2ee584a42"
BUNGIE_CLIENT_SECRET = "GOWj7qxqS3RXXD7d1pohg4AX2nGl1-nM8abdlah55EY"

[[d1_databases]]
binding = "DB"
database_name = "armoury-db"
database_id = "b86f47d1-46a0-4423-a46e-0392d3a6dc5d"

[[kv_namespaces]]
binding = "MANIFEST_CACHE"
id = "8795299e485a470096586c57f720a5eb"
