name = "armoury-crate"
compatibility_date = "2024-04-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# [[d1_databases]]
# binding = "DB"
# database_name = "armoury-db"
# database_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" # Placeholder

# [[kv_namespaces]]
# binding = "MANIFEST_CACHE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" # Placeholder
